version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db_data:${DB_DATA:-/var/lib/mysql}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - db
    networks:
      - backend

  web:
    build: .
    container_name: web
    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_PORT_SECURE:-443}:443
    volumes:
      - ./htdocs:${WEB_DOCROOT:-/var/www/html}
      - ./config:/config
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
